version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ".:/var/www/html:cached"
      - "./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "80:80"
      - "8000:80"
    depends_on:
        - api
    networks:
        - takebook-network
    working_dir: /var/www/html
  db:
    container_name: takebook_db
    image: mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - takebook-network
    command: mysqld --default-authentication-plugin=mysql_native_password
  api:
    container_name: takebook_api
    build: .
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached
    networks:
      - takebook-network
    working_dir: "/var/www/html"
  redis:
    image: redis:alpine
    ports:
      - "${BROADCAST_REDIS_CONNECTION}:6379"

  composer:
    image: prooph/composer:7.3
    working_dir: "/var/www/html"
    command: install --no-interaction
    volumes:
      - .:/var/www/html:cached
      - ~/.composer:/tmp:cached
networks:
  takebook-network:
    external:
      name: takebook-administrativo_takebook-network
