<?php


namespace App\Repositories\User;


use App\Entities\Auth\User;
use App\Repositories\Repository;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserRepository extends Repository
{
    public function __construct()
    {
        $this->model = new User();
    }

    public function create(array $data)
    {
        $data['password'] = Hash::make($data['password']);
        return parent::create($data);
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function update(array $data, $id)
    {
        if (array_key_exists('password', $data)) {
            unset($data['password']);
        }
        return parent::update($data, $id);
    }
}
