<?php


namespace App\Repositories\User;


use App\Entities\Auth\User;
use App\Repositories\Repository;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class UserRepository extends Repository
{
    public function __construct()
    {
        $this->model = new User();
    }

    public function create(array $data)
    {
        unset($data['is_admin']);
        $data['password'] = Hash::make($data['password']);

        if (array_key_exists('avatar_file', $data)) {
				$file = $data['avatar_file'];
				$fileName = "avatars/" . Str::random(16) . "-avatar." . $file->getClientOriginalExtension();

				Storage::put($fileName, file_get_contents($file));
		}
        return parent::create($data);
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function update(array $data, $id)
    {
        unset($data['password']);
        unset($data['is_admin']);

        return parent::update($data, $id);
    }
}
