<?php


namespace App\Repositories\Book;


use App\Entities\Book\Book;
use App\Repositories\Repository;
use Illuminate\Support\Facades\Auth;

class BookRepository extends Repository
{
    public function __construct()
    {
        $this->model = new Book();
    }

    public function create(array $data)
    {
        unset($data['status']);
        $book = parent::create($data);

        foreach ($data['categories'] as $category) {
            $this->attach($book->id, $category, 'categories');
        }

        return $book;
    }

    public function update(array $data, $id)
    {
        if (!Auth::user()->is_admin) {
            unset($data['status']);
        }
        return parent::update($data, $id); // TODO: Change the autogenerated stub
    }

    public function attach($idParent, $idChild, $relation, $data = [])
    {
        return parent::attach($idParent, $idChild, $relation, $data); // TODO: Change the autogenerated stub
    }
}
