<?php


namespace App\Repositories\Book;


use App\Entities\Book\Book;
use App\Repositories\Repository;

class BookRepository extends Repository
{
    public function __construct()
    {
        $this->model = new Book();
    }

    public function create(array $data)
    {

        $book = parent::create($data);

        foreach ($data['categories'] as $category) {
            $this->attach($book->id, $category, 'categories');
        }

        return $book;
    }

    public function attach($idParent, $idChild, $relation, $data = [])
    {
        return parent::attach($idParent, $idChild, $relation, $data); // TODO: Change the autogenerated stub
    }
}
